---
title: "Autoregressive Behavior of Aviation Weather Forecasts: Statistics"
author: "Oliver M. Haynold & Neal Ylitalo"
date: "`r Sys.Date()`"
#output: html_document
output:
  md_document:
    variant: markdown_github
---

```{r setup, include=FALSE}
library(readr)
library(dplyr)
library(ggplot2)
library(usmap)
library(palettes)


knitr::opts_chunk$set(echo = FALSE)
```

```{r}
lines <- read_csv("../data/histograms/full_set/hist YearlyStations.csv.zip",
                  col_types = cols(
                    aerodrome = "f",
                    year="i",
                    variable="f",
                    previous="n",
                    current="n",
                    final="n",
                    count="i"
                  ))

stations <- read_csv("../config/stations.csv", 
                     col_types = cols(
                       station = "f",
                       name = "c",
                       latitude = "n",
                       longitude = "n",
                       center = "f"
                     )) %>%
              rename(aerodrome=station) %>%
              select(-center)
```


For now, this is just same sample analysis as a framework.

# Some Summary Statistics

We have loaded `r nrow(lines)` data lines for `r length(unique(lines$aerodrome))` aerodromes for configuration tiny_data.

## Distribution of Wind Speeds

```{r}
  wind_speed_hist <- lines %>% 
      filter(variable=="wind_speed" & current < 50) %>%
      group_by(current) %>%
      summarize(count=sum(count)) %>%
      ungroup()

 print(
   ggplot(wind_speed_hist, aes(x=current)) + 
     geom_histogram(aes(weight=count), binwidth = 1) +
     labs(title="Histogram of Wind Speeds", x="Wind Speed kts", y="Count") +
     theme_bw()
   )
```


```{r}
wind_speed_avg <- lines %>% 
      filter(variable=="wind_speed") %>%
      group_by(aerodrome) %>%
      summarize(current=mean(current)) %>%
      ungroup() %>%
      left_join(stations, by=c("aerodrome")) %>%
      filter(substr(aerodrome, 1, 1)=="K" | substr(aerodrome, 1, 2)=="PA" | substr(aerodrome, 1, 2)=="PH") 


plot_usmap(fill="grey") +
  geom_sf(data=usmap_transform(wind_speed_avg, input_names = c("longitude", "latitude")),
             aes(colour=current)) +
  scale_colour_gradientn(colours = heat.colors(10)) +
  labs(title = "Average wind forecast speed by location", colour="Knots")
```






