# Settings that apply to all configurations unless overridden
general:
  year_to: 2024
  parallel: true

# Process our full dataset
full_set:
  year_from: 2010

# Run on a very limited test dataset to save time
tiny_data:
  year_from: 2023
  parallel: false
  # noinspection SpellCheckingInspection
  aerodromes:
    - KABE
    - KABI
    - KABQ
    - KABR
    - KABY
    - KACK
    - KACT
    - KACV
    - KACY
    - KADF
